{% set version = "1.6.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-radiant.data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/radiant.data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/radiant.data/radiant.data_{{ version }}.tar.gz
  sha256: 9525e844c4c0abe804d4e68031d9982012c6d0cb1f664e35fdad64caeeb5a55c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-arrow >=12.0.1
    - r-base64enc
    - r-broom >=0.5.2
    - r-bslib >=0.5.0
    - r-car >=3.0_0
    - r-curl >=2.5
    - r-dplyr >=1.1.2
    - r-dt >=0.28
    - r-ggplot2 >=3.4.2
    - r-glue >=1.3.0
    - r-import >=1.1.0
    - r-jsonlite >=1.0
    - r-knitr >=1.20
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-markdown >=1.7
    - r-mass
    - r-patchwork >=1.0.0
    - r-plotly >=4.7.1
    - r-png
    - r-psych >=1.8.4
    - r-randomizr >=0.20.0
    - r-readr >=1.1.1
    - r-readxl >=1.0.0
    - r-rlang >=0.4.10
    - r-rmarkdown >=2.22
    - r-rstudioapi >=0.7
    - r-scales >=0.4.0
    - r-shiny >=1.8.1
    - r-shinyace >=0.4.1
    - r-shinyfiles >=0.9.1
    - r-stringi >=1.2.4
    - r-tibble >=1.4.2
    - r-tidyr >=0.8.2
    - r-writexl >=0.2
  run:
    - r-base
    - r-arrow >=12.0.1
    - r-base64enc
    - r-broom >=0.5.2
    - r-bslib >=0.5.0
    - r-car >=3.0_0
    - r-curl >=2.5
    - r-dplyr >=1.1.2
    - r-dt >=0.28
    - r-ggplot2 >=3.4.2
    - r-glue >=1.3.0
    - r-import >=1.1.0
    - r-jsonlite >=1.0
    - r-knitr >=1.20
    - r-lubridate >=1.7.4
    - r-magrittr >=1.5
    - r-markdown >=1.7
    - r-mass
    - r-patchwork >=1.0.0
    - r-plotly >=4.7.1
    - r-png
    - r-psych >=1.8.4
    - r-randomizr >=0.20.0
    - r-readr >=1.1.1
    - r-readxl >=1.0.0
    - r-rlang >=0.4.10
    - r-rmarkdown >=2.22
    - r-rstudioapi >=0.7
    - r-scales >=0.4.0
    - r-shiny >=1.8.1
    - r-shinyace >=0.4.1
    - r-shinyfiles >=0.9.1
    - r-stringi >=1.2.4
    - r-tibble >=1.4.2
    - r-tidyr >=0.8.2
    - r-writexl >=0.2

test:
  commands:
    - $R -e "library('radiant.data')"           # [not win]
    - "\"%R%\" -e \"library('radiant.data')\""  # [win]

about:
  home: https://radiant-rstats.github.io/radiant.data
  dev_url: https://github.com/radiant-rstats/radiant.data
  doc_url: https://radiant-rstats.github.io/docs
  license: AGPL-3.0-only
  summary: The Radiant Data menu includes interfaces for loading, saving, viewing, visualizing, summarizing, transforming, and combining data. It also contains functionality to generate reproducible reports of the analyses conducted in the application.
  license_family: AGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
