appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qFvyjwDLlpwFZQKCpVCatyyvSPavViNrwrGlITYCWbTBbcIi5Ww4ol53m6BD7yYZ/jdMxGxx2SB5WYJjO+TAn99gUtUvwEZKsexkDD8eyN2n9iiWlv20XkHL848g6X8GzVR0Jqw1yaK+rx2jRoUaxb98deRi2MaD7z4D+h0HCynN3vxktFlo2jvbjx91NTv7OM/SLA0VxzzwNGkebYEyXmlZH0cbLc+z7oP4YUKt+2n9QxPtF+tSUgqqdG8iLfzyYPWOlv0rBUU2VkqGGfWjQbNuVyKioJjAk939gLynMvDFpEjpDCkDO5A2gQERYPqlB58CpXK8IJz4gFQevZhA9pFvtiSIhG0d5nbyFf65O0IMQvY8j4/go6eeS7+LWMzFmicLtU+iR5h0fBV4LIcVT8/wWPW0D96xLyg+bpi8MjwEV4IIZdUJ+vUOwL4xQ2Io4jvrk6nhgvyb1tHCtCS7QulolUh2LU3AUNW9vuP8V2scxuqxXVgDzZFKNKUbAfwdfm4zAd//QUg8Qbi/15bxLS+nyjK0kqIh9UBqcPh2LdYbSeruxuHJOeiWSTfevSeQnk3r2DnPrwO1RlQBGK7Y+BVxHjjSe+tcpBrF4vs5rs6HJ8QDZz40EaRNrmGgJqzqnhx7+6Q7fch6OvHMmBMSJTNCG6x8vttG7msX8o4lXGA=}
bot:
  automerge: true
